// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'reflector_dispatcher_test.dart' as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Foo',
            r'.Foo',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13],
            const <int>[
              14,
              15,
              16,
              17,
              18,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ([greetName = 'Stranger']) =>
                  b ? prefix0.Foo(greetName) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'greetName', 32773, 0, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.MethodMirrorImpl(r'hi', 131074, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'hello', 131074, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'greet', 131074, 0, -1, -1, -1, null,
            const <int>[0], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'add', 131074, 0, -1, -1, -1, null,
            const <int>[1, 2], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'subtract', 131074, 0, -1, -1, -1, null,
            const <int>[3, 4], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'subtractNamed', 131074, 0, -1, -1, -1, null,
            const <int>[5, 6], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'throwError', 65538, 0, -1, -1, -1, null,
            const <int>[7, 8], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'typeerror', 65538, 0, -1, -1, -1, null,
            const <int>[9], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'divzerotest', 131074, 0, -1, -1, -1, null,
            const <int>[10], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'usePrivateAdd', 131074, 0, -1, -1, -1, null,
            const <int>[11, 12], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 11),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 12),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[13],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, -1, -1, null, const <int>[15],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1, null,
            const <int>[16], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'name', 36870, 3, const prefix0.Reflector(), -1,
            -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'a', 32774, 4, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'b', 32774, 4, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'a', 32774, 5, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'b', 32774, 5, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'minuend', 40966, 6, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #minuend),
        r.ParameterMirrorImpl(
            r'subtrahend',
            40966,
            6,
            const prefix0.Reflector(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #subtrahend),
        r.ParameterMirrorImpl(r'a', 32774, 7, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'b', 32774, 7, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'a', 16390, 8, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'a', 32774, 9, const prefix0.Reflector(), -1, -1,
            -1, null, null, null, null),
        r.ParameterMirrorImpl(r'a', 32774, 10, const prefix0.Reflector(), -1,
            -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'b', 32774, 10, const prefix0.Reflector(), -1,
            -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(
            r'greetName',
            38918,
            13,
            const prefix0.Reflector(),
            -1,
            -1,
            -1,
            null,
            null,
            'Stranger',
            null),
        r.ParameterMirrorImpl(r'_greetName', 32870, 12,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'other', 32774, 14, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 16,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix0.Foo],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'hi': (dynamic instance) => instance.hi,
        r'hello': (dynamic instance) => instance.hello,
        r'greet': (dynamic instance) => instance.greet,
        r'add': (dynamic instance) => instance.add,
        r'subtract': (dynamic instance) => instance.subtract,
        r'subtractNamed': (dynamic instance) => instance.subtractNamed,
        r'throwError': (dynamic instance) => instance.throwError,
        r'typeerror': (dynamic instance) => instance.typeerror,
        r'divzerotest': (dynamic instance) => instance.divzerotest,
        r'usePrivateAdd': (dynamic instance) => instance.usePrivateAdd,
        r'greetName': (dynamic instance) => instance.greetName
      },
      {r'greetName=': (dynamic instance, value) => instance.greetName = value},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
